// images
import blogImg1 from "../images/blog/img-1.webp";
import blogImg2 from "../images/blog/img-2.jpg";
import blogImg3 from "../images/blog/img-3.webp";

import blogSingleImg1 from "../images/blog-details/1.jpg";
import blogSingleImg2 from "../images/blog-details/2.jpg";
import blogSingleImg3 from "../images/blog-details/3.jpg";

const blogs = [
  {
    id: "1",
    title: "Cost-Effective Equipment Solutions for IVF Startups",
    title2: "Building Your Laboratory on a Budget",
    tag: "Equipment",
    slug: "cost-effective-equipment-solutions-for-startup-ivf-clinics",
    screens: blogImg1,
    description:
      "Strategic recommendations for new IVF clinics looking to establish a high-quality laboratory while managing equipment costs effectively.",
    author: "Daniel Carter",
    create_at: "Jan 12, 2025",
    blogSingleImg: blogSingleImg3,
    comment: "17",
    day: "12",
    month: "JAN",
    blClass: "format-standard-image",
    animation: "1200",
  },
  //   {
  //     id: "1",
  //     title: "Advancements in Incubation Technology for IVF",
  //     title2: "How Modern Incubators Are Transforming IVF Success Rates",
  //     tag: "Equipment",
  //     slug: "advancements-in-incubation-technology-for-ivf-labs",
  //     screens: blogImg1,
  //     description:
  //       "Explore the latest developments in IVF incubation technology and how they contribute to improved embryo development and clinical outcomes.",
  //     author: "Rebecca Zhang",
  //     create_at: "May 08, 2025",
  //     blogSingleImg: blogSingleImg1,
  //     comment: "23",
  //     day: "08",
  //     month: "MAY",
  //     blClass: "format-standard-image",
  //     animation: "1200",
  //   },
  {
    id: "2",
    title: "Selecting the Right Consumables for Embryo Culture",
    title2: "Quality Considerations for Modern IVF Laboratory Consumables",
    tag: "Consumables",
    slug: "selecting-the-right-consumables-for-embryo-culture",
    screens: blogImg2,
    description:
      "A comprehensive guide to choosing the optimal consumables for your IVF laboratory to maximize embryo development and clinical outcomes.",
    author: "Mark Henderson",
    create_at: "Apr 15, 2025",
    blogSingleImg: blogSingleImg2,
    comment: "18",
    day: "15",
    month: "APR",
    blClass: "format-standard-image",
    animation: "1200",
  },
  {
    id: "3",
    title: "Optimizing Your IVF Lab Setup for Maximum Efficiency",
    title2: "Design Principles for Modern Fertility Clinics",
    tag: "Lab Design",
    slug: "optimizing-your-ivf-lab-setup-for-maximum-efficiency",
    screens: blogImg3,
    description:
      "Best practices for designing and equipping your IVF laboratory workspace to enhance workflow, reduce contamination risks, and improve success rates.",
    author: "Thomas Reid",
    create_at: "Mar 22, 2025",
    blogSingleImg: blogSingleImg3,
    comment: "29",
    day: "22",
    month: "MAR",
    blClass: "format-standard-image",
    animation: "1200",
  },
  // {
  //     id: '4',
  //     title: 'The Impact of Culture Media Selection on Embryo Development',
  //     title2: 'Understanding the Science Behind Specialized IVF Media',
  //     tag: 'Consumables',
  //     slug: 'impact-of-culture-media-selection-on-embryo-development',
  //     screens: blogImg1,
  //     description: 'A detailed analysis of how different culture media formulations affect embryo development, with recommendations for optimizing your laboratory protocols.',
  //     author: 'Jennifer Parker',
  //     create_at: 'Feb 17, 2025',
  //     blogSingleImg: blogSingleImg1,
  //     comment: '15',
  //     day: '17',
  //     month: 'FEB',
  //     blClass: 'format-standard-image',
  //     animation: '1200',
  // },
  // {
  //     id: '5',
  //     title: 'Maintaining Quality Control in Your IVF Laboratory',
  //     title2: 'Essential Procedures for Consistent Results',
  //     tag: 'Best Practices',
  //     slug: 'maintaining-quality-control-in-your-ivf-laboratory',
  //     screens: blogImg2,
  //     description: 'Key quality control measures and equipment validation procedures to ensure consistent, high-quality results in your IVF laboratory.',
  //     author: 'Lisa Wong',
  //     create_at: 'Jan 30, 2025',
  //     blogSingleImg: blogSingleImg2,
  //     comment: '21',
  //     day: '30',
  //     month: 'JAN',
  //     blClass: 'format-standard-image',
  //     animation: '1200',
  // },
  // {
  //     id: '6',
  //     title: 'Cost-Effective Equipment Solutions for Startup IVF Clinics',
  //     title2: 'Building Your Laboratory on a Budget',
  //     tag: 'Equipment',
  //     slug: 'cost-effective-equipment-solutions-for-startup-ivf-clinics',
  //     screens: blogImg3,
  //     description: 'Strategic recommendations for new IVF clinics looking to establish a high-quality laboratory while managing equipment costs effectively.',
  //     author: 'Daniel Carter',
  //     create_at: 'Jan 12, 2025',
  //     blogSingleImg: blogSingleImg3,
  //     comment: '17',
  //     day: '12',
  //     month: 'JAN',
  //     blClass: 'format-standard-image',
  //     animation: '1200',
  // },
];

export default blogs;
